<?php

use App\Models\Option;
use Illuminate\Database\Seeder;

class OptionsTableSeeder extends Seeder
{
    public function run()
    {
    	DB::table("options")->delete();
        Option::create([ 'question_id' =>  1, 'option' => 'Floppy']);
        Option::create([ 'question_id' =>  1, 'option' => 'Virus']);
        Option::create([ 'question_id' =>  1, 'option' => 'Java']);
        Option::create([ 'question_id' =>  1, 'option' => 'Monitor']);
        Option::create([ 'question_id' =>  2, 'option' => '192.168.1.1']);
        Option::create([ 'question_id' =>  2, 'option' => '192.168.111.1111']);
        Option::create([ 'question_id' =>  2, 'option' => '192.168.900.1']);
        Option::create([ 'question_id' =>  2, 'option' => '192.900.168.1']);
        Option::create([ 'question_id' =>  3, 'option' => 'World Wide Web']);
        Option::create([ 'question_id' =>  3, 'option' => 'Netscape Navigator']);
        Option::create([ 'question_id' =>  3, 'option' => 'Internet Explorer']);
        Option::create([ 'question_id' =>  3, 'option' => 'Safari']);
        Option::create([ 'question_id' =>  4, 'option' => 'Application']);
        Option::create([ 'question_id' =>  4, 'option' => 'Session']);
        Option::create([ 'question_id' =>  4, 'option' => 'Cookie']);
        Option::create([ 'question_id' =>  4, 'option' => 'QueryString']);
        Option::create([ 'question_id' =>  5, 'option' => 'contact.website.info']);
        Option::create([ 'question_id' =>  5, 'option' => 'contactwebsite.info']);
        Option::create([ 'question_id' =>  5, 'option' => 'contact@website.info']);
        Option::create([ 'question_id' =>  5, 'option' => 'contact@website@info']);
        Option::create([ 'question_id' =>  6, 'option' => 'Hypertext Transfer Protocol']);
        Option::create([ 'question_id' =>  6, 'option' => 'Hypertext Transfer Plotter']);
        Option::create([ 'question_id' =>  6, 'option' => 'Head Tail Transfer Plot']);
        Option::create([ 'question_id' =>  6, 'option' => 'Head Tail Transfer Protocol']);
        Option::create([ 'question_id' =>  7, 'option' => 'Bit']);
        Option::create([ 'question_id' =>  7, 'option' => 'Byte']);
        Option::create([ 'question_id' =>  7, 'option' => 'Newton']);
        Option::create([ 'question_id' =>  7, 'option' => 'Mega byte']);
        Option::create([ 'question_id' =>  8, 'option' => 'TCS']);
        Option::create([ 'question_id' =>  8, 'option' => 'IBM']);
        Option::create([ 'question_id' =>  8, 'option' => 'Microsoft']);
        Option::create([ 'question_id' =>  8, 'option' => 'Satyam']);
        Option::create([ 'question_id' =>  9, 'option' => 'Jumber Verbose Mechanics']);
        Option::create([ 'question_id' =>  9, 'option' => 'A part of IIS']);
        Option::create([ 'question_id' =>  9, 'option' => 'Java Virtual Machine']);
        Option::create([ 'question_id' =>  9, 'option' => '.Net Framework']);
        Option::create([ 'question_id' => 10, 'option' => 'Operating System']);
        Option::create([ 'question_id' => 10, 'option' => 'Storage Device']);
        Option::create([ 'question_id' => 10, 'option' => 'Processor']);
        Option::create([ 'question_id' => 10, 'option' => 'Output Device']);
        Option::create([ 'question_id' => 11, 'option' => 'Application Software']);
        Option::create([ 'question_id' => 11, 'option' => 'Motherboard']);
        Option::create([ 'question_id' => 11, 'option' => 'Operating System']);
        Option::create([ 'question_id' => 11, 'option' => 'RAM']);
        Option::create([ 'question_id' => 12, 'option' => 'Video']);
        Option::create([ 'question_id' => 12, 'option' => 'Sound']);
        Option::create([ 'question_id' => 12, 'option' => 'Image']);
        Option::create([ 'question_id' => 12, 'option' => 'Word Document']);
        Option::create([ 'question_id' => 13, 'option' => 'An Application software']);
        Option::create([ 'question_id' => 13, 'option' => 'A Process']);
        Option::create([ 'question_id' => 13, 'option' => 'A System Software']);
        Option::create([ 'question_id' => 13, 'option' => 'A Document']);
        Option::create([ 'question_id' => 14, 'option' => 'Low level language']);
        Option::create([ 'question_id' => 14, 'option' => 'Assembly language']);
        Option::create([ 'question_id' => 14, 'option' => 'High level language']);
        Option::create([ 'question_id' => 14, 'option' => 'Source code']);
        Option::create([ 'question_id' => 15, 'option' => 'File Transfer Protocol']);
        Option::create([ 'question_id' => 15, 'option' => 'File Transfer Program']);
        Option::create([ 'question_id' => 15, 'option' => 'File Thread Protocol']);
        Option::create([ 'question_id' => 15, 'option' => 'File Thread Program Option Four']);
        Option::create([ 'question_id' => 16, 'option' => 'Apple Inc.']);
        Option::create([ 'question_id' => 16, 'option' => 'Microsoft']);
        Option::create([ 'question_id' => 16, 'option' => 'Oracle Corporation']);
        Option::create([ 'question_id' => 16, 'option' => 'IBM']);
        Option::create([ 'question_id' => 17, 'option' => 'GWS']);
        Option::create([ 'question_id' => 17, 'option' => 'IIS 5.0']);
        Option::create([ 'question_id' => 17, 'option' => 'CERN httpd']);
        Option::create([ 'question_id' => 17, 'option' => 'nginx']);
        Option::create([ 'question_id' => 18, 'option' => 'Black Carbon Copy']);
        Option::create([ 'question_id' => 18, 'option' => 'Blind Carbon Copy']);
        Option::create([ 'question_id' => 18, 'option' => 'Business Computer Center']);
        Option::create([ 'question_id' => 18, 'option' => 'Business Computer Card']);
        Option::create([ 'question_id' => 19, 'option' => 'Application Software']);
        Option::create([ 'question_id' => 19, 'option' => 'System Software']);
        Option::create([ 'question_id' => 19, 'option' => 'Operating System']);
        Option::create([ 'question_id' => 19, 'option' => 'Scanner']);
        Option::create([ 'question_id' => 20, 'option' => 'Bill Board']);
        Option::create([ 'question_id' => 20, 'option' => 'James Gosling']);
        Option::create([ 'question_id' => 20, 'option' => 'Jame Smith']);
        Option::create([ 'question_id' => 20, 'option' => 'Sabeer Bhatia']);
        Option::create([ 'question_id' => 21, 'option' => 'Operating System']);
        Option::create([ 'question_id' => 21, 'option' => 'Web Browser']);
        Option::create([ 'question_id' => 21, 'option' => 'Microsoft Word']);
        Option::create([ 'question_id' => 21, 'option' => 'Microsoft Excel']);
        Option::create([ 'question_id' => 22, 'option' => 'MS Word and Spreadsheet']);
        Option::create([ 'question_id' => 22, 'option' => 'Transaction and Application']);
        Option::create([ 'question_id' => 22, 'option' => 'Microsoft and Mac OS']);
        Option::create([ 'question_id' => 22, 'option' => 'System and Application']);
        Option::create([ 'question_id' => 23, 'option' => '1000']);
        Option::create([ 'question_id' => 23, 'option' => '1001']);
        Option::create([ 'question_id' => 23, 'option' => '100']);
        Option::create([ 'question_id' => 23, 'option' => '1024']);
        Option::create([ 'question_id' => 24, 'option' => 'Information']);
        Option::create([ 'question_id' => 24, 'option' => 'Output']);
        Option::create([ 'question_id' => 24, 'option' => 'Data']);
        Option::create([ 'question_id' => 24, 'option' => 'Query']);
        Option::create([ 'question_id' => 25, 'option' => 'Internet Engineering Task Force']);
        Option::create([ 'question_id' => 25, 'option' => 'ICANN']);
        Option::create([ 'question_id' => 25, 'option' => 'Internet Architecture Board']);
        Option::create([ 'question_id' => 25, 'option' => 'No one owns it']);
        Option::create([ 'question_id' => 26, 'option' => 'Ctrl + P']);
        Option::create([ 'question_id' => 26, 'option' => 'Shift + P']);
        Option::create([ 'question_id' => 26, 'option' => 'Alt + P']);
        Option::create([ 'question_id' => 26, 'option' => 'Shift + PP']);
        Option::create([ 'question_id' => 27, 'option' => 'Application']);
        Option::create([ 'question_id' => 27, 'option' => 'Session']);
        Option::create([ 'question_id' => 27, 'option' => 'Cookie']);
        Option::create([ 'question_id' => 27, 'option' => 'QueryString']);
        Option::create([ 'question_id' => 28, 'option' => 'Compiler']);
        Option::create([ 'question_id' => 28, 'option' => 'Operating System']);
        Option::create([ 'question_id' => 28, 'option' => 'Input Device']);
        Option::create([ 'question_id' => 28, 'option' => 'Programming Language']);
        Option::create([ 'question_id' => 29, 'option' => 'Temporary file']);
        Option::create([ 'question_id' => 29, 'option' => 'Image file']);
        Option::create([ 'question_id' => 29, 'option' => 'Video file']);
        Option::create([ 'question_id' => 29, 'option' => 'Text file']);
        Option::create([ 'question_id' => 30, 'option' => 'Storing']);
        Option::create([ 'question_id' => 30, 'option' => 'Processing']);
        Option::create([ 'question_id' => 30, 'option' => 'Deletion']);
        Option::create([ 'question_id' => 30, 'option' => 'Organizing']);
        Option::create([ 'question_id' => 31, 'option' => 'Better Integrated Operating System']);
        Option::create([ 'question_id' => 31, 'option' => 'Basic Input Output System']);
        Option::create([ 'question_id' => 31, 'option' => 'Battery Integrated Operating Setup']);
        Option::create([ 'question_id' => 31, 'option' => 'Backup Input Output System']);
        Option::create([ 'question_id' => 32, 'option' => 'Least Area Network']);
        Option::create([ 'question_id' => 32, 'option' => 'Large Area Network']);
        Option::create([ 'question_id' => 32, 'option' => 'Local Area Network']);
        Option::create([ 'question_id' => 32, 'option' => 'Length Area Network']);
        Option::create([ 'question_id' => 33, 'option' => 'Satellite']);
        Option::create([ 'question_id' => 33, 'option' => 'Switch']);
        Option::create([ 'question_id' => 33, 'option' => 'Optical Fibre']);
        Option::create([ 'question_id' => 33, 'option' => 'Modem']);
        Option::create([ 'question_id' => 34, 'option' => 'Sytem file']);
        Option::create([ 'question_id' => 34, 'option' => 'MS Office document']);
        Option::create([ 'question_id' => 34, 'option' => 'Video file']);
        Option::create([ 'question_id' => 34, 'option' => 'Image file']);
        Option::create([ 'question_id' => 35, 'option' => 'Processor']);
        Option::create([ 'question_id' => 35, 'option' => 'Operating System']);
        Option::create([ 'question_id' => 35, 'option' => 'MS Word']);
        Option::create([ 'question_id' => 35, 'option' => 'Animation']);
        Option::create([ 'question_id' => 36, 'option' => 'DVD']);
        Option::create([ 'question_id' => 36, 'option' => 'Hard Disk']);
        Option::create([ 'question_id' => 36, 'option' => 'Floppy Disk']);
        Option::create([ 'question_id' => 36, 'option' => 'Mouse']);
        Option::create([ 'question_id' => 37, 'option' => 'GMail']);
        Option::create([ 'question_id' => 37, 'option' => 'Yahoo Mail']);
        Option::create([ 'question_id' => 37, 'option' => 'Hotmail']);
        Option::create([ 'question_id' => 37, 'option' => 'Rediff Mail']);
        Option::create([ 'question_id' => 38, 'option' => 'Laptops']);
        Option::create([ 'question_id' => 38, 'option' => 'Mainframe Computers']);
        Option::create([ 'question_id' => 38, 'option' => 'Mini Computers']);
        Option::create([ 'question_id' => 38, 'option' => 'Super Computers']);
        Option::create([ 'question_id' => 39, 'option' => 'Electronic track system']);
        Option::create([ 'question_id' => 39, 'option' => 'Part of register']);
        Option::create([ 'question_id' => 39, 'option' => 'Special memory']);
        Option::create([ 'question_id' => 39, 'option' => 'Part of a CPU']);
        Option::create([ 'question_id' => 40, 'option' => '5']);
        Option::create([ 'question_id' => 40, 'option' => '6']);
        Option::create([ 'question_id' => 40, 'option' => '7']);
        Option::create([ 'question_id' => 40, 'option' => '8']);
        Option::create([ 'question_id' => 41, 'option' => 'Apache']);
        Option::create([ 'question_id' => 41, 'option' => 'IIS']);
        Option::create([ 'question_id' => 41, 'option' => 'Jigsaw']);
        Option::create([ 'question_id' => 41, 'option' => 'Zaob']);
        Option::create([ 'question_id' => 42, 'option' => 'IBM 405']);
        Option::create([ 'question_id' => 42, 'option' => 'Zuse Z3']);
        Option::create([ 'question_id' => 42, 'option' => 'ENIAC']);
        Option::create([ 'question_id' => 42, 'option' => 'CSIRAC']);
        Option::create([ 'question_id' => 43, 'option' => 'Computed Gateway Interface']);
        Option::create([ 'question_id' => 43, 'option' => 'Compliant Gateway Interface']);
        Option::create([ 'question_id' => 43, 'option' => 'Case Gateway Interface']);
        Option::create([ 'question_id' => 43, 'option' => 'Common Gateway Interface']);
        Option::create([ 'question_id' => 44, 'option' => 'Oracle']);
        Option::create([ 'question_id' => 44, 'option' => 'AJAX']);
        Option::create([ 'question_id' => 44, 'option' => 'MySQL']);
        Option::create([ 'question_id' => 44, 'option' => 'SQL Server']);
        Option::create([ 'question_id' => 45, 'option' => 'Mouse']);
        Option::create([ 'question_id' => 45, 'option' => 'Hard Disk']);
        Option::create([ 'question_id' => 45, 'option' => 'Microprocessor']);
        Option::create([ 'question_id' => 45, 'option' => 'DVD']);
        Option::create([ 'question_id' => 46, 'option' => 'Param']);
        Option::create([ 'question_id' => 46, 'option' => 'Super 301']);
        Option::create([ 'question_id' => 46, 'option' => 'Compaq Presario']);
        Option::create([ 'question_id' => 46, 'option' => 'CRAY YMP']);
        Option::create([ 'question_id' => 47, 'option' => 'Internet']);
        Option::create([ 'question_id' => 47, 'option' => 'Linux']);
        Option::create([ 'question_id' => 47, 'option' => 'Unix']);
        Option::create([ 'question_id' => 47, 'option' => 'Windows']);
        Option::create([ 'question_id' => 48, 'option' => '10']);
        Option::create([ 'question_id' => 48, 'option' => '9']);
        Option::create([ 'question_id' => 48, 'option' => '0']);
        Option::create([ 'question_id' => 48, 'option' => '1']);
        Option::create([ 'question_id' => 49, 'option' => 'When x is less than one hundred']);
        Option::create([ 'question_id' => 49, 'option' => 'When x is greater than one hundred']);
        Option::create([ 'question_id' => 49, 'option' => 'When x is equal to one hundred']);
        Option::create([ 'question_id' => 49, 'option' => 'While it wishes']);
        Option::create([ 'question_id' => 50, 'option' => 'For']);
        Option::create([ 'question_id' => 50, 'option' => 'Do while']);
        Option::create([ 'question_id' => 50, 'option' => 'While']);
        Option::create([ 'question_id' => 50, 'option' => 'Repeat Until']);

    	Option::create([ 'question_id' => 51, 'option' => 'Apple'     ]);
    	Option::create([ 'question_id' => 51, 'option' => 'Ball' 	  ]);
    	Option::create([ 'question_id' => 51, 'option' => 'Cat' 	  ]);
    	Option::create([ 'question_id' => 51, 'option' => 'Dog' 	  ]);
    	Option::create([ 'question_id' => 52, 'option' => 'Mouse' 	  ]);
    	Option::create([ 'question_id' => 52, 'option' => 'Tiger' 	  ]);
    	Option::create([ 'question_id' => 52, 'option' => 'Bear' 	  ]);
    	Option::create([ 'question_id' => 52, 'option' => 'Lion' 	  ]);
    	Option::create([ 'question_id' => 53, 'option' => 'Pink' 	  ]);
    	Option::create([ 'question_id' => 53, 'option' => 'Cool' 	  ]);
    	Option::create([ 'question_id' => 53, 'option' => 'Hot'       ]);
    	Option::create([ 'question_id' => 53, 'option' => 'Yellow' 	  ]);
    	Option::create([ 'question_id' => 54, 'option' => 'Red'  	  ]);
    	Option::create([ 'question_id' => 54, 'option' => 'Cheetah'   ]);
    	Option::create([ 'question_id' => 54, 'option' => 'Temporary' ]);
    	Option::create([ 'question_id' => 54, 'option' => 'Digital'   ]);
    	Option::create([ 'question_id' => 55, 'option' => 'RAM' 	  ]);
    	Option::create([ 'question_id' => 55, 'option' => 'ECMAScript']);
    	Option::create([ 'question_id' => 55, 'option' => 'Bother' 	  ]);
    	Option::create([ 'question_id' => 55, 'option' => 'Mother' 	  ]);
    	Option::create([ 'question_id' => 56, 'option' => 'Father' 	  ]);
    	Option::create([ 'question_id' => 56, 'option' => 'Zoo'       ]);
    	Option::create([ 'question_id' => 56, 'option' => 'PHP' 	  ]);
    	Option::create([ 'question_id' => 56, 'option' => 'Laravel'	  ]);
    }
}
